apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tilt-demo
spec:
  template:
    metadata:
      annotations:
        # Bound number of replicas to enable Tilt features
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
      - image: registry.kn-tilt.majordemo.com/tilt-demo-2022:first
        command: ['no-reload']
        env:
          # See https://github.com/facebook/create-react-app/blob/9673858a3715287c40aef9e800c431c7d45c05a2/packages/react-scripts/config/webpackDevServer.config.js#L25
          # This allows us to proxy the `react start` dev process, rather than needing to `react build` it each time (which would also lose live reload)
          - name: DANGEROUSLY_DISABLE_HOST_CHECK
            value: "true"
        ports:
          - containerPort: 3000
            protocol: TCP
